### ISSUE TITLE
Backend: Set up architecture and initial structure

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/active-businesses-locations#1]
#### Describe the feature request
Set up the **architecture** and initial **structure** of the API.

The architecture is going to be based on **DDD** and the development process is going to be based on **TDD**.

#### Describe the solution you'd like
As DDD is going to be applied, the domain layers should be configured, refer to the following structure:

- domain
   - infra
   - interfaces
   - services
      - tests 
      - service
   - dtos 

Must follow the principles of SOLID and configure a container for dependencies. 

#### Tasks
- [x] Set up structure with [Express](https://expressjs.com/) as the Web Framework.
- [x] Configure code styles tools such as Editor Config and Eslint.
- [x] Configure husky and lint-staged to run scripts based on git hooks.
- [x] Add base folders with `.gitkeep` to be used on the next pull requests.
 - [x] Configure [TypeORM](https://typeorm.io/#/) and use Mongo as the database.
- [x] Add README.md with base instructions to run the API.
- [x] Configure dependencies container

**Comment by gabrielsanttana** [comment]
Hi, Laura!

**Comment by gabrielsanttana** [comment]
Hi, Laura! 

Is there gonna be a frontend application to be built along with this API?

**Comment by gabrielsanttana** [comment]
Hi, Laura!

Is this project open for contributions?

**Comment by gabrielsanttana** [comment]
Hi, Laura!

Is this project open for contributions?
